FROM fedora:28
%%%OS%%%
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN echo fubar > /etc/machine-id
RUN dnf install -y dnf-utils
RUN dnf config-manager --add-repo https://people.freedesktop.org/~hughsient/fedora/utopia.repo
RUN dnf --enablerepo=updates-testing -y update
RUN dnf install -y libxmlb-devel
RUN echo fubar > /etc/machine-id
%%%INSTALL_DEPENDENCIES_COMMAND%%%
RUN mkdir /build
WORKDIR /build
COPY . .
CMD ["./contrib/ci/fedora.sh"]
